"""add staff invitations table

Revision ID: 83acee197b0a
Revises: 
Create Date: 2026-07-19 16:08:36.018316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83acee197b0a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_invitations_token'), 'staff_invitations', ['token'], unique=True)
    op.drop_index(op.f('idx_customer_phone'), table_name='customers')
    op.drop_index(op.f('idx_customer_telegram'), table_name='customers')
    op.alter_column('loyalty_rules', 'evaluation_period_days',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Rolling window in days for visit/spend thresholds. NULL means all-time.',
               existing_nullable=True)
    op.drop_index(op.f('idx_refresh_token'), table_name='refresh_tokens')
    op.drop_index(op.f('idx_reward_customer'), table_name='rewards')
    op.drop_index(op.f('idx_reward_status'), table_name='rewards')
    op.drop_index(op.f('idx_service_order_items_order'), table_name='service_order_items')
    op.drop_index(op.f('idx_service_order_items_service'), table_name='service_order_items')
    op.drop_index(op.f('idx_order_customer'), table_name='service_orders')
    op.drop_index(op.f('idx_order_status'), table_name='service_orders')
    op.drop_index(op.f('idx_sms_status'), table_name='sms_logs')
    op.drop_index(op.f('idx_telegram_status'), table_name='telegram_logs')
    op.drop_index(op.f('idx_visit_customer'), table_name='visits')
    op.drop_index(op.f('idx_visit_date'), table_name='visits')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_visit_date'), 'visits', ['visit_date'], unique=False)
    op.create_index(op.f('idx_visit_customer'), 'visits', ['customer_id'], unique=False)
    op.create_index(op.f('idx_telegram_status'), 'telegram_logs', ['delivery_status'], unique=False)
    op.create_index(op.f('idx_sms_status'), 'sms_logs', ['delivery_status'], unique=False)
    op.create_index(op.f('idx_order_status'), 'service_orders', ['status'], unique=False)
    op.create_index(op.f('idx_order_customer'), 'service_orders', ['customer_id'], unique=False)
    op.create_index(op.f('idx_service_order_items_service'), 'service_order_items', ['service_id'], unique=False)
    op.create_index(op.f('idx_service_order_items_order'), 'service_order_items', ['service_order_id'], unique=False)
    op.create_index(op.f('idx_reward_status'), 'rewards', ['status'], unique=False)
    op.create_index(op.f('idx_reward_customer'), 'rewards', ['customer_id'], unique=False)
    op.create_index(op.f('idx_refresh_token'), 'refresh_tokens', ['token_hash'], unique=False)
    op.alter_column('loyalty_rules', 'evaluation_period_days',
               existing_type=sa.INTEGER(),
               comment='Rolling window in days for visit/spend thresholds. NULL means all-time.',
               existing_nullable=True)
    op.create_index(op.f('idx_customer_telegram'), 'customers', ['telegram_id'], unique=False)
    op.create_index(op.f('idx_customer_phone'), 'customers', ['phone_number'], unique=False)
    op.drop_index(op.f('ix_staff_invitations_token'), table_name='staff_invitations')
    op.drop_table('staff_invitations')
    # ### end Alembic commands ###
